name: Publish VS Code Extension

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'idfedorov09/bl-language-support'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --pat $VSCE_PAT
